micronaut:
    application:
        name: grpcDemoClientKotlin
grpc:
    server:
        port: 50052
    channels:
        tokenApi:
            target: "http://localhost:50051"
            plaintext: true